### ISSUE TITLE
list content by name instead of uuid

### ISSUE THREAD

**Issue by naturallymitchell** [foundpatterns/lighttouch-html-interface#2]

**Comment by Arnaz87** [comment]
Fixed by https://github.com/foundpatterns/lighttouch-html-interface/commit/bf1168164e337c46d3c3267720f63002642be3ac

Other important changes that make that work are in https://github.com/foundpatterns/lighttouch/commit/8c6ff6127509a5beca4adcd9e9c995b1331e2908
