### ISSUE TITLE
show documents referencing this document underneath

### ISSUE THREAD

**Issue by naturallymitchell** [foundpatterns/lighttouch-html-interface#3]

**Comment by Arnaz87** [comment]
All documents regardless of their model? What about show a link for each model that can reference the current model, eg. in `profile/[uuid]` there would be a link "Keys" pointing to `profile/[uuid]/key` which has all the keys referencing that profile (what I call the key sobdocuments of the profile)

**Comment by naturallymitchell** [comment]
Preferably both.

**Comment by Arnaz87** [comment]
Should be just one as having both is redundant. Any can be done but the easiest is what i'm proposing, the link to subdocuments.

**Comment by Arnaz87** [comment]
https://github.com/foundpatterns/lighttouch-html-interface/commit/7f0944f41f35763e0bfb95b4cc746c46cab347a4

https://github.com/foundpatterns/lighttouch/commit/adab08814e9da0168a425e6e7ff1e6d4864b3045
